services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: nome-do-container
    ports:
      - "8090:80"
    working_dir: /var/www/html
    volumes:
      #aqui vc muda o caminho para o projeto que você quer rodar
      - ./pasta-clonada:/var/www/html
      - ./.docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost/ || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s

  #aqui o mailhog para rodar email tests
  mailhog:
    image: mailhog/mailhog
    container_name: proweb-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
